[profile.default]
solc-version = "0.8.27"
optimizer = false # faster compilation
optimizer-runs = 10_000_000
extra_output = ["storageLayout", "metadata"]
evm-version = "cancun"

[fuzz]
runs = 10_000
fail_on_revert = false

[profile.smt.model_checker]
engine = "chc"
timeout = 100
targets = [
    "assert",
]

[profile.smt.model_checker.contracts]
"~/projects/halmos-sandbox/test/21_monotonic.t.sol" = [ 'Monotonic' ]

